name: PUBLISH

on: [push]
# on:
#   release:
#     types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: https://npm.pkg.github.com/
          scope: '@astrosat'
      - run: |
          yarn install
          yarn test
          yarn build
          yarn publish
        env:
          CI: true
          GITHUB_REGISTRY_TOKEN: ${{secrets.GITHUB_REGISTRY_TOKEN}}
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
